[package]
name = "renameplus_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
renameplus = {path = ".."}
native-dialog = "0.6"
iced = { version = "0.5.2", features = ["default_system_font", "tokio"] }
tokio = "1.22.0"
anyhow = { version = "1.0.66", features = ["backtrace"] }
flexi_logger = "0.24.1"
itertools = "0.10.5"
