[package]
name = "renameplus_gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = { version = "0.19", features = ["egui-wgpu", "wgpu"] }
egui_extras = "0.19"
miette = {version="5.3", features = ["fancy"]}
thiserror = "1.0"
renameplus = {path = ".."}
native-dialog = "0.6"
