[package]
name = "autorename"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.2"
clap_logger = "0.3"
log = "0.4"
miette = {version="5.3", features = ["fancy"]}

[profile.release]
strip = true